version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  zookeeper:
    build:
      context: .
      dockerfile: zookeeper-Dockerfile
    ports:
      - "2181:2181"
  kafka:
    depends_on: 
      - zookeeper
    build:
      context: .
      dockerfile: kafka-Dockerfile
    ports:
      - "9092:9092"
  http-server:
    depends_on: 
      - redis
      - kafka
    build:
      context: .
      dockerfile: server-Dockerfile
    ports:
      - "8080:8080"