version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  zookeeper:
    build: ./zookeeper-Dockerfile
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-Dockerfile
    ports:
      - "9092:9092"
  http-server:
    build: .
    ports:
      - "8080:8080"